Feature/rename parameters of venn diagram
togostanza/metastanza-devel pull request #10
Opened 2022-11-09 14:33 UTC by penqe

ベン図スタンザのパラメータ名変更・機能改修を行いました。
同時に、common.scss に共通的なスタイルを記述を加えました。

2022-11-09 15:09 UTC, neznayer requested changes
@penqe ありがとうございます！ 
細かいですが、いくつかの修正をお願いしたいです：
 - `custom-css-url` は、最新の仕様ですと、 `misc-custom_css_url` という名前になっていますので、しゅせいをお願いいたします。
 - 行18〜　と　行235 〜　のコメントは、不要でしたら、削除をお願いしまいです。

2022-11-09 15:11 UTC, neznayer commented on stanzas/venn-diagram/index.js
>    // colorSeries;
不要のコメントを削除をお願いいたします。

2022-11-09 16:10 UTC, penqe commented
@neznayer コメントありがとうございます。修正しました。
l. 18〜 のコメントは、フィールド宣言に変更しました（なくても動くのですが）。

2022-11-10 14:18 UTC, neznayer commented
ありがとうございます 🙇‍♂️

2022-11-10 14:18 UTC, neznayer approved these changes

2022-11-10 14:19 UTC, merged