Feature/tree
togostanza/metastanza-devel pull request #17
Opened 2022-11-21 02:28 UTC by YukikoNoda

font-familyをscss内のmainで描画するのではなく、svg内で描画する方法に変更しました。

2022-11-21 22:58 UTC, penqe approved these changes
ありがとうございます

2022-11-28 06:29 UTC, penqe approved these changes
ありがとうございます

2022-11-28 07:30 UTC, neznayer approved these changes
ありがとうございます。

2022-11-28 07:34 UTC, neznayer commented on stanzas/tree/style.scss
> +  font-family: var(--togostanza-fonts-font_family);
`font-family` は、`common.scss` になっていたので、ここで指定しなくてもいいかと思います。
```suggestion
```

2022-11-28 07:35 UTC, neznayer requested changes
ありがとうございます。
細かいところの一箇所がありましたので、コメントしました。 🙇‍♂️

2022-12-05 07:29 UTC, YukikoNoda commented
Parameters, Stylesをparams一覧表に則り整理をし直しました。ご確認をお願いします。

[現在の実装状況の表](https://docs.google.com/spreadsheets/d/18-vFq3qAEqLkYYNbSvxSg_YFx9MKJCM2wAh_5f0HGNA/edit#gid=1943616436)

2022-12-27 02:16 UTC, neznayer approved these changes
ありがとうございます！ 🙇‍♂️

2022-12-27 02:17 UTC, merged