Feature/heatmap
togostanza/metastanza-devel pull request #18
Opened 2022-11-21 09:30 UTC by YukikoNoda

legendの描画方法を、表示(左上固定)・非表示のbooleanに変更しました。

2022-11-21 22:54 UTC, penqe approved these changes
ありがとうございます

2022-11-28 06:25 UTC, neznayer requested changes
ありがとうございます！
細かいところを修正していただきたいので、コメントしました。

2022-11-28 06:33 UTC, neznayer commented
- `axis-title_padding` paramを、`-x-`, `-y-` 軸に分けていただいても大丈夫でしょうか。(`axis-x-title_padding`, `axis-y-title_padding`)

2022-11-28 10:14 UTC, YukikoNoda commented
`axis-title_padding param`を、-x-, -y- 軸に分けました。(`axis-x-title_padding`, `axis-y-title_padding`)

また、legendの中のopacityの記述により、heatmapのlegendの位置bugが生じていたので、if文を追加することで修正を行いました。

2022-11-29 04:09 UTC, neznayer commented
> `axis-title_padding param`を、-x-, -y- 軸に分けました。(`axis-x-title_padding`, `axis-y-title_padding`)
> 
> また、legendの中のopacityの記述により、heatmapのlegendの位置bugが生じていたので、if文を追加することで修正を行いました。

@YukikoNoda ありがとうございます！

2022-11-29 04:09 UTC, neznayer approved these changes
ありがとうございます！

2022-11-29 04:10 UTC, merged