Feature/sunburst
togostanza/metastanza-devel pull request #26
Opened 2022-11-28 02:45 UTC by YukikoNoda

parameter一覧表を参考に変更しています。
機能していないものもあります。今後修正予定です。

[参考Spreadsheet](https://docs.google.com/spreadsheets/d/18-vFq3qAEqLkYYNbSvxSg_YFx9MKJCM2wAh_5f0HGNA/edit#gid=331245145)

2022-11-28 06:38 UTC, neznayer commented on stanzas/sunburst/metadata.json
> +      "stanza:key": "node-title_key",
すみません、`node-**label**_key` に変更していただいてもよろしいでしょうか。（他のstanza は、 node に書いている「文書」は `label` という名前が多いので。。）

2022-11-28 06:44 UTC, neznayer commented on stanzas/sunburst/metadata.json
> +      "stanza:key": "node-value_key",
`node-value_key` は、`required: true` であるはずです (`value` 値がないと描画できないなはずなので)
　ちなみに、今は、 `node-value_key` を消しても、ダイアグラムが消えなく、何もエラーになっていないので、もしかして、コードの中にどこかで `data.n`みたいにのではないでしょうか。
ご確認いただけますでしょうか。

2022-11-28 06:46 UTC, neznayer commented on stanzas/sunburst/metadata.json
> +      "stanza:key": "node-title_key",
node-title_key（node-label_key） を消しても、 ラベルが消えないので、ハードコードになっているのではないでしょうか。

2022-11-28 06:47 UTC, neznayer commented on stanzas/sunburst/metadata.json
> +      "stanza:key": "--togostanza-outline-padding",
`--togostanza-outline-padding`は今ですと、なぜか効かないですね。。

2022-11-28 06:48 UTC, penqe reviewed
これも custom css url のパラメータ名が違いますかね

2022-11-28 06:51 UTC, neznayer commented on stanzas/sunburst/index.js
> +    const height = parseFloat(css("--togostanza-outline-height"));
駒街ですが、統一して頂けますでしょうか。 ( parseFloat のほうに)

2022-11-28 07:01 UTC, neznayer commented on stanzas/sunburst/index.js
>      const scalingMethod = this.params["scaling"];
指定されなかったら "Natural"にfallbackされるようにお願いします。（`required` ではないので）
```suggestion
    const scalingMethod = this.params["scaling"] || "Natural"
```

2022-11-28 07:04 UTC, neznayer requested changes
ありがとうございます。
コメントしました。

2022-11-30 10:11 UTC, YukikoNoda commented
paddingをstyleで調整できるよう変更できるようにしました。
`node-value_key`のハードコードを変更しました。

次に、`node-label_key`のハードコードを変更します。

2022-12-01 08:53 UTC, YukikoNoda commented
`node-label_key`のハードコードではなくしました。

他にも細かく質問をしたいことがありますので、[Google Sheets](https://docs.google.com/spreadsheets/d/18-vFq3qAEqLkYYNbSvxSg_YFx9MKJCM2wAh_5f0HGNA/edit#gid=331245145)に記述しております。

2022-12-27 02:04 UTC, neznayer commented on stanzas/sunburst/index.js
>      }
ここは、　`ColorGenerator` が使えますね。

2022-12-27 02:06 UTC, neznayer requested changes
ありがとうございます！
細かいけど、コメントを残しました。 🙇‍♂️

2022-12-28 01:29 UTC, YukikoNoda commented
@neznayer colorGeneratorを使用して書き換えました。
`const colorScale = colorGenerator.stanzaColor;`では行うことができなかったので、別の方法で行いました。
ご確認をお願いします。

2022-12-28 04:25 UTC, neznayer approved these changes
ありがとうございます！

2022-12-28 04:25 UTC, merged