Feature/text
togostanza/metastanza-devel pull request #27
Opened 2022-11-28 04:30 UTC by YukikoNoda

parameter一覧表を参考に変更しています。
機能していないものもあります。今後修正予定です。

[参考Spreadsheet](https://docs.google.com/spreadsheets/d/18-vFq3qAEqLkYYNbSvxSg_YFx9MKJCM2wAh_5f0HGNA/edit#gid=1873633112)

2022-11-28 06:32 UTC, penqe reviewed
`custom_css_url` は `misc-` が付きませんでしたか？

2022-11-28 06:52 UTC, YukikoNoda commented
@penqe 他のスタンザもなしで行っていたので全て変更します🙇🏻‍♀️

2022-11-28 07:41 UTC, neznayer commented on stanzas/text/metadata.json
>        "stanza:key": "highlight-css-url",
（念の為、ここにコメントします）
先ほど永野さんの指摘のように、`highlight_css_url`に変更をお願いいたします。
```suggestion
      "stanza:key": "highlight-css-url",
```

2022-11-28 07:43 UTC, neznayer requested changes
ありがとうございます！ 
`highlight_css_url` だけを修正をお願いします。🙇‍♂️

2022-11-28 08:01 UTC, YukikoNoda commented
paramsを`highlight_css_url`に変更しました。

2022-11-28 09:55 UTC, neznayer commented on stanzas/text/index.js
> +    const padding = +css("--togostanza-outline-padding");
`padding` style.scss で当てはめても大丈夫です。（JS にpadding がなくてもいいのではないかと思います）
```css
main {
  padding: var(--togostanza-outline-padding);
}
```

2022-11-30 07:10 UTC, YukikoNoda commented
paddingをstyle.scssに記述しました。
しかし、width, heightをstyle.scssに記述しても反映できない理由がわかりませんでした。

2022-12-01 10:14 UTC, YukikoNoda commented
width, heightをstyle.scssに記述しました。
他の[不明点リスト](https://docs.google.com/spreadsheets/d/18-vFq3qAEqLkYYNbSvxSg_YFx9MKJCM2wAh_5f0HGNA/edit#gid=1873633112)

2022-12-12 01:48 UTC, YukikoNoda commented
width, heightを.container内で設定することで、menuアイコンの位置が正常に反映されないbugを解消しました。

2022-12-20 04:34 UTC, penqe approved these changes
ありがとうございます

2022-12-27 01:53 UTC, neznayer approved these changes
ありがとうございます！ 🙇‍♂️

2022-12-27 01:53 UTC, merged